mysql:
  enabled: false
  host: "localhost"
  user: "root"
  pass: "admin"
  dbName: "csmo"
  port: 3306
matchmaking: 10 #if players have + or - this elo they wil be able to match together
minPlayers: 2
spawn:
  ==: org.bukkit.Location
  world: world
  x: -3
  y: 83
  z: -23
  pitch: 0.0
  yaw: 0.0
serverip: salamanderia.ddns.net